name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
    inputs:
      test_name:
        description: 'Test case name'
        required: true
        default: 'com.Bai_23'
  # [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Maven
        run: sudo apt-get install -y maven

      - name: Install Chrome
        run:  |
          sudo apt-get update
          sudo apt-get --only-upgrade install google-chrome-stable

      - name: CI test
        run:  |
          mvn clean test -Dtest=${{ github.event.inputs.test_name }} -DfailIfNoTests=false

      - name: Report
        uses: actions/upload-artifact@v3
        with:
          name: test-report-${{ github.run_number }}
          path: |
            if: ${{ contains(github.event.inputs.test_name, 'Cucumber') }}
            target/cucumber-reports/cucumber.html
            if: ${{ ! contains(github.event.inputs.test_name, 'Cucumber') }}
            target/surefire-reports/emailable-report.html